FLASK_APP=app
FLASK_ENV=deveployment
FLASK_DEBUG=0

MYSQL_HOST=127.0.0.1
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PASSWORD=123456

ADMIN_USERNAME=admin
ADMIN_EMAIL=admin@example.com
ADMIN_USERNAME=admin123
